//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaszynaPi.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MaszynaPi.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Opcje]
        ///Połączenie=0
        ///Inkrementacja=0
        ///Logiczne=0
        ///Arytmetyczne=0
        ///Stos=0
        ///RejestrX=0
        ///RejestrY=0
        ///Przerwania=0
        ///Wejście=0
        ///Znaczniki=0
        ///Adres=5
        ///Kod=3
        ///[Rozkazy]
        ///Liczba=8
        ///Nazwa1=stp
        ///Nazwa2=add
        ///Nazwa3=sub
        ///Nazwa4=load
        ///Nazwa5=stor
        ///Nazwa6=jmp
        ///Nazwa7=blz
        ///Nazwa8=bez
        ///[stp]
        ///Linie=5
        ///Linia1=// end program
        ///Linia2=INSTRUCTION STP;
        ///Linia3=Arguments 0;
        ///Linia4=rd od iins icit;
        ///Linia5=stop;
        ///[add]
        ///Linie=4
        ///Linia1=INSTRUCTION ADD;
        ///Linia2=rd od iins icit;
        ///Linia3=oa ia;
        ///Linia4=rd od ialu add iacc oit ia; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Base {
            get {
                return ResourceManager.GetString("Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Opcje]
        ///Połączenie=0
        ///Inkrementacja=0
        ///Logiczne=0
        ///Arytmetyczne=0
        ///Stos=0
        ///RejestrX=0
        ///RejestrY=0
        ///Przerwania=0
        ///Wejście=0
        ///Znaczniki=0
        ///Adres=5
        ///Kod=3
        ///[Rozkazy]
        ///Liczba=8
        ///Nazwa1=stp
        ///Nazwa2=dod
        ///Nazwa3=ode
        ///Nazwa4=pob
        ///Nazwa5=ład
        ///Nazwa6=sob
        ///Nazwa7=som
        ///Nazwa8=soz
        ///[stp]
        ///Linie=5
        ///Linia1=// zakończenie programu
        ///Linia2=ROZKAZ STP;
        ///Linia3=Argumenty 0;
        ///Linia4=czyt wys wei il;
        ///Linia5=stop;
        ///[dod]
        ///Linie=4
        ///Linia1=ROZKAZ DOD;
        ///Linia2=czyt wys wei il;
        ///Linia3=wyad wea;
        ///Linia4=czyt wys weja dod weak wyl  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Podstawa {
            get {
                return ResourceManager.GetString("Podstawa", resourceCulture);
            }
        }
    }
}
