//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaszynaPi.Properties {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MaszynaPi.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu [Opcje]
        ///Połączenie=0
        ///Inkrementacja=0
        ///Logiczne=0
        ///Arytmetyczne=0
        ///Stos=0
        ///RejestrX=0
        ///RejestrY=0
        ///Przerwania=0
        ///Wejście=0
        ///Znaczniki=0
        ///Adres=5
        ///Kod=3
        ///[Rozkazy]
        ///Liczba=8
        ///Nazwa1=stp
        ///Nazwa2=add
        ///Nazwa3=sub
        ///Nazwa4=load
        ///Nazwa5=stor
        ///Nazwa6=jmp
        ///Nazwa7=blz
        ///Nazwa8=bez
        ///[stp]
        ///Linie=5
        ///Linia1=// zakończenie programu
        ///Linia2=INSTRUCTION STP;
        ///Linia3=Arguments 0;
        ///Linia4=rd od iins icit;
        ///Linia5=stop;
        ///[add]
        ///Linie=4
        ///Linia1=INSTRUCTION ADD;
        ///Linia2=rd od iins icit;
        ///Linia3=oa ia;
        ///Linia4=rd od ialu add iac [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        public static string Base {
            get {
                return ResourceManager.GetString("Base", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu [Opcje]
        ///Połączenie=0
        ///Inkrementacja=0
        ///Logiczne=0
        ///Arytmetyczne=0
        ///Stos=0
        ///RejestrX=0
        ///RejestrY=0
        ///Przerwania=0
        ///Wejście=0
        ///Znaczniki=0
        ///Adres=5
        ///Kod=3
        ///[Rozkazy]
        ///Liczba=8
        ///Nazwa1=stp
        ///Nazwa2=dod
        ///Nazwa3=ode
        ///Nazwa4=pob
        ///Nazwa5=ład
        ///Nazwa6=sob
        ///Nazwa7=som
        ///Nazwa8=soz
        ///[stp]
        ///Linie=5
        ///Linia1=// zakończenie programu
        ///Linia2=ROZKAZ STP;
        ///Linia3=Argumenty 0;
        ///Linia4=czyt wys wei il;
        ///Linia5=stop;
        ///[dod]
        ///Linie=4
        ///Linia1=ROZKAZ DOD;
        ///Linia2=czyt wys wei il;
        ///Linia3=wyad wea;
        ///Linia4=czyt wys weja dod weak wyl  [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        public static string Podstawa {
            get {
                return ResourceManager.GetString("Podstawa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SignalWireArrow {
            get {
                object obj = ResourceManager.GetObject("SignalWireArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SignalWireArrowD {
            get {
                object obj = ResourceManager.GetObject("SignalWireArrowD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SignalWireArrowL {
            get {
                object obj = ResourceManager.GetObject("SignalWireArrowL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SignalWireArrowU {
            get {
                object obj = ResourceManager.GetObject("SignalWireArrowU", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SignalWireD {
            get {
                object obj = ResourceManager.GetObject("SignalWireD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SignalWireL {
            get {
                object obj = ResourceManager.GetObject("SignalWireL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SignalWireR {
            get {
                object obj = ResourceManager.GetObject("SignalWireR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SignalWireU {
            get {
                object obj = ResourceManager.GetObject("SignalWireU", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
